Spike: Change ExtensionContainerScope to be from single instance instead of static
castleproject/Windsor pull request #567
Opened 2020-11-20 20:20 UTC by generik0

2020-11-20 20:20 UTC, generik0 commented
@jonorossi Spike for discussion, not ment to be merged, nor build

2020-11-24 05:40 UTC, jonorossi requested changes

2020-11-24 05:40 UTC, jonorossi commented on src/Castle.Windsor/MicroKernel/Lifestyle/ScopedLifestyleManager.cs
> +				var container = Kernel.Resolve<IScopeContainer>();
What is `IScopeContainer`?

2020-11-24 05:40 UTC, jonorossi commented on src/Castle.Windsor/MicroKernel/Lifestyle/Scoped/IScopeAccessor.cs
> +		bool HasKernelScoping { get; }
This is obviously a breaking change to `IScopeAccessor`, implemented by both Windsor facilities and users. It also is counter to the goal of scopes within a container.

2020-11-24 05:40 UTC, jonorossi commented on src/Castle.Windsor.Extensions.DependencyInjection/WindsorServiceProviderFactoryBase.cs
> +			container.Register(Component
Registering an `ILifetimeScope` in the container is likely going to cause all sorts of pain.

2020-11-25 07:46 UTC, closed without merging